### PR TITLE
pick requirements.txt even if both Pipfile present

### PR DESCRIPTION
**Pull request by TimSimpsonR**
I wrote a big nasty error message that told users to either specify
Pipfile or requirements.txt if both were present. Unfortunately that
breaks a ton of existing Fleece usage so this change warns if both file
types are present.

### CODE REVIEW

**Comment by Gifflen** [comment]
Thanks for the quick fix

**Comment by Gifflen** [comment]
Actually, can you bump the version as well?

**Comment by TimSimpsonR** [comment]
@Gifflen Totally. Should I do it as part of this PR?

**Comment by Gifflen** [comment]
Yes, thanks.

**Comment by TimSimpsonR** [comment]
Done, merging after Circle passes

**Pull request merged**
