### PR TITLE
AWS X-Ray integration for Lambda/Python

### PR DESCRIPTION
**Pull request by szilveszter**
Excerpt from the module docs to explain what this is about:

> This module bridges the gap of missing Python support in the AWS X-Ray Lambda integration.
> 
> After enabling active tracing under Advanced settings on the Configuration tab of your Lambda function in the AWS Console (or using the `update_function_configuration` API call), you can mark any function or method for tracing by using the `@trace_xray_subsegment` decorator.
> 
> This module also provides wrappers for boto and requests so that any AWS API call, or HTTP request will be automatically traced by X-Ray, but you have to explicitly allow this behavior by calling `monkey_patch_botocore_for_xray` and/or `monkey_patch_requests_for_xray`. The best place to do this would be the main handler module where the Lambda entry point is defined.

### CODE REVIEW

**Comment by ryandub** [comment]
This looks awesome! Thanks @szilveszter ! 👍

**Comment by ryandub** [comment]
@szilveszter - Will you add a quick docs section to the README for this? It can just be similar to what is there for the boto and requests wrappers.

**Comment by Gifflen** [comment]
Thanks for putting this together!! I have the same request as Ryan. Once thats in place I'll happily merge/publish

**Comment by szilveszter** [comment]
Thanks for the feedback, I just updated the README, could you check it, please?

**Pull request merged**
