### PR TITLE
Add command for interactive shell with AWS credentials

### PR DESCRIPTION
**Pull request by szilveszter**
I like to play around with some ideas in an interactive Python shell, so it makes my life so much easier when I have something available with the correct AWS credentials set up.

If you have more advanced shells (like bpython or IPython) installed, they will be used instead of the plain old one.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
I'm +1 on the idea, as I need this for my workflow as well.

But instead of duplicating a lot of the logic already in `run`, would it make more sense to add `--interactive` option to that command? I have started a python shell with `fleece run python`, and that works mostly okay, there is just some weirdness around the handling of stdout and stderr that I think can be fixed if `--interactive` is chosen.

**Comment by Gifflen** [comment]
Really like this idea as well. 👍

**Comment by szilveszter** [comment]
@miguelgrinberg Sure, I can do that. I was trying to do `fleece run bpython`, and failed miserably, hence this PR. Would it be okay with you to keep the `fleece shell` command (as an alias)? Takes less to type than `fleece run --interactive` (or even `fleece run -i`)

**Comment by szilveszter** [comment]
@miguelgrinberg Ended up not doing the alias, because it seemed non-trivial work not worth spending on a single character difference in length :)

**Comment by miguelgrinberg** [comment]
@szilveszter Looks good.

What do you think about making the `-i` option more generic? What if I want to start a bash shell provisioned with creds instead of python, for example?

Honestly, when I suggested the `-i` option I was thinking this option would just set the correct settings for stdout/stderr. Pretty much like the `-it` combination does it for `docker run`.

**Comment by ryandub** [comment]
@szilveszter @miguelgrinberg - Do we have an agreed solution? I'd like to see this to continue to move forward.

**Comment by szilveszter** [comment]
@ryandub Sorry about the lack of follow up on this. It turned out that this is not as simple as just switching around stdin/stdout/stderr values, and would take significantly more effort to achieve the functionality @miguelgrinberg requested.

I'd suggest having a separate `shell` command (in order to make the intention/use case explicit) with as little code duplication as possible, and implement a proper `run -i` solution at some point in the future. Does this sound acceptable to everyone?

**Comment by miguelgrinberg** [comment]
Would using [pty.spawn()](https://docs.python.org/3.6/library/pty.html) help with the tty problems?

**Comment by szilveszter** [comment]
Thanks for the hint. It worked okay-ish for simple interactive scripts (`python`, but still had to exit the child process twice in order to stop, for some reason), but `bpython` wouldn't even run. Also looked into other solutions, such as [ptyprocess](https://pypi.python.org/pypi/ptyprocess), but that didn't work either.

**Comment by szilveszter** [comment]
#68 solves my use case, closing this one.

**Pull request closed without merging**
